export const FONT_PAIRINGS = [
  { heading: "'Bungee', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Bungee Shade', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik Wet Paint', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik Moonrocks', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fredoka One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Modak', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Staatliches', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Creepster', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Eater', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fascinate Inline', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Black Ops One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Butcherman', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Press Start 2P', monospace", body: "'Inter', sans-serif" },
  { heading: "'Permanent Marker', cursive", body: "'Inter', sans-serif" },
  { heading: "'Bangers', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Frijole', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Knewave', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Megrim', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Monofett', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Monoton', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Orbitron', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Smokum', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Spirax', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Vampiro One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Grumpy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nosifer', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Faster One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Freckle Face', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fruktur', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Finger Paint', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fontdiner Swanky', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gloria Hallelujah', cursive", body: "'Inter', sans-serif" },
  { heading: "'Henny Penny', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kranky', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mouse Memoirs', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Passion One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Plaster', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rock Salt', cursive", body: "'Inter', sans-serif" },
  { heading: "'Sedgwick Ave Display', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sigmar One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Slackey', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sniglet', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stardos Stencil', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Trade Winds', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Wendy One', sans-serif", body: "'Inter', sans-serif" },
  // Even MORE weird fonts!
  { heading: "'Amatic SC', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Barrio', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Bigshot One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Cinzel Decorative', serif", body: "'Inter', sans-serif" },
  { heading: "'Londrina Outline', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Londrina Shadow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Syncopate', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Caveat', cursive", body: "'Inter', sans-serif" },
  { heading: "'Dancing Script', cursive", body: "'Inter', sans-serif" },
  { heading: "'Lobster', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pacifico', cursive", body: "'Inter', sans-serif" },
  { heading: "'Shadows Into Light', cursive", body: "'Inter', sans-serif" },
  { heading: "'Zilla Slab Highlight', serif", body: "'Inter', sans-serif" },
  { heading: "'Raleway Dots', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Uncial Antiqua', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Irish Grover', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kalam', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Love Ya Like A Sister', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Overlock SC', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ribeye Marrow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Shrikhand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sonsie One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Trochut', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Righteous', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rye', serif", body: "'Inter', sans-serif" },
  { heading: "'Wallpoet', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Special Elite', monospace", body: "'Inter', sans-serif" },
  { heading: "'Flamenco', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ultra', serif", body: "'Inter', sans-serif" },
  // ESOTERIC & EXPERIMENTAL FONTS
  { heading: "'Almendra Display', serif", body: "'Inter', sans-serif" },
  { heading: "'Almendra SC', serif", body: "'Inter', sans-serif" },
  { heading: "'Amita', serif", body: "'Inter', sans-serif" },
  { heading: "'Angkor', serif", body: "'Inter', sans-serif" },
  { heading: "'Anton', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Arbutus', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Arbutus Slab', serif", body: "'Inter', sans-serif" },
  { heading: "'Aref Ruqaa Ink', serif", body: "'Inter', sans-serif" },
  { heading: "'Audiowide', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Bai Jamjuree', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Bevan', serif", body: "'Inter', sans-serif" },
  { heading: "'Bokor', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Bonbon', cursive", body: "'Inter', sans-serif" },
  { heading: "'Bungee Inline', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Butterfly Kids', cursive", body: "'Inter', sans-serif" },
  { heading: "'Cabin Sketch', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Caesar Dressing', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Carter One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Chango', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Charmonman', cursive", body: "'Inter', sans-serif" },
  { heading: "'Chela One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Cherry Swash', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Chewy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Chicle', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Chonburi', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Codystar', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Combo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Comfortaa', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Concert One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Condiment', cursive", body: "'Inter', sans-serif" },
  { heading: "'Content', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Contrail One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Corben', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Cormorant Garamond', serif", body: "'Inter', sans-serif" },
  { heading: "'Cormorant SC', serif", body: "'Inter', sans-serif" },
  { heading: "'Cormorant Unicase', serif", body: "'Inter', sans-serif" },
  { heading: "'Courgette', cursive", body: "'Inter', sans-serif" },
  { heading: "'Covered By Your Grace', cursive", body: "'Inter', sans-serif" },
  { heading: "'Crafty Girls', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Creepster', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Crimson Text', serif", body: "'Inter', sans-serif" },
  { heading: "'Croissant One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Crushed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Cuprum', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Damion', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Dangrek', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Dawning of a New Day', cursive", body: "'Inter', sans-serif" },
  { heading: "'Days One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Delius Unicase', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Devonshire', cursive", body: "'Inter', sans-serif" },
  { heading: "'Diplomata', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Diplomata SC', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Do Hyeon', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Dokdo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Domine', serif", body: "'Inter', sans-serif" },
  { heading: "'Donegal One', serif", body: "'Inter', sans-serif" },
  { heading: "'Doppio One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Dorsa', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Dr Sugiyama', cursive", body: "'Inter', sans-serif" },
  { heading: "'Dynalight', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Eagle Lake', serif", body: "'Inter', sans-serif" },
  { heading: "'East Sea Dokdo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Eczar', serif", body: "'Inter', sans-serif" },
  { heading: "'Elsie', serif", body: "'Inter', sans-serif" },
  { heading: "'Elsie Swash Caps', serif", body: "'Inter', sans-serif" },
  { heading: "'Emblema One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Emilys Candy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Engagement', serif", body: "'Inter', sans-serif" },
  { heading: "'Englebert', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Erica One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Esteban', serif", body: "'Inter', sans-serif" },
  { heading: "'Euphoria Script', cursive", body: "'Inter', sans-serif" },
  { heading: "'Ewert', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Exo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Expletus Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fascinate', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Federant', serif", body: "'Inter', sans-serif" },
  { heading: "'Felipa', cursive", body: "'Inter', sans-serif" },
  { heading: "'Fjalla One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fjord One', serif", body: "'Inter', sans-serif" },
  { heading: "'Flavors', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fondamento', serif", body: "'Inter', sans-serif" },
  { heading: "'Fontdiner Swanky', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Forum', serif", body: "'Inter', sans-serif" },
  { heading: "'Francois One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Freckle Face', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fredericka the Great', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fredoka One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Freehand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fresca', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Frijole', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fruktur', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Fugaz One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gafata', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Galada', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Galindo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gamja Flower', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Geostar', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Geostar Fill', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Germania One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gidugu', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gilda Display', serif", body: "'Inter', sans-serif" },
  { heading: "'Give You Glory', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Glass Antiqua', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Glegoo', serif", body: "'Inter', sans-serif" },
  { heading: "'Gloria Hallelujah', cursive", body: "'Inter', sans-serif" },
  { heading: "'Goblin One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gochi Hand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gorditas', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Goudy Bookletter 1911', serif", body: "'Inter', sans-serif" },
  { heading: "'Graduate', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Grand Hotel', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gravitas One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Great Vibes', cursive", body: "'Inter', sans-serif" },
  { heading: "'Griffy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gruppo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gudea', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Gurajada', serif", body: "'Inter', sans-serif" },
  { heading: "'Habibi', serif", body: "'Inter', sans-serif" },
  { heading: "'Hachi Maru Pop', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Halant', serif", body: "'Inter', sans-serif" },
  { heading: "'Hammersmith One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Hanalei', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Hanalei Fill', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Handlee', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Hanuman', serif", body: "'Inter', sans-serif" },
  { heading: "'Happy Monkey', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Headland One', serif", body: "'Inter', sans-serif" },
  { heading: "'Henny Penny', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Herr Von Muellerhoff', cursive", body: "'Inter', sans-serif" },
  { heading: "'Hi Melody', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Holtwood One SC', serif", body: "'Inter', sans-serif" },
  { heading: "'Homemade Apple', cursive", body: "'Inter', sans-serif" },
  { heading: "'Homenaje', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Iceberg', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Iceland', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Imprima', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Inconsolata', monospace", body: "'Inter', sans-serif" },
  { heading: "'Inder', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Indie Flower', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Inika', serif", body: "'Inter', sans-serif" },
  { heading: "'Inknut Antiqua', serif", body: "'Inter', sans-serif" },
  { heading: "'Irish Grover', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Istok Web', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Italiana', serif", body: "'Inter', sans-serif" },
  { heading: "'Italianno', cursive", body: "'Inter', sans-serif" },
  { heading: "'Itim', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Jacques Francois', serif", body: "'Inter', sans-serif" },
  { heading: "'Jacques Francois Shadow', serif", body: "'Inter', sans-serif" },
  { heading: "'Jaldi', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Jim Nightshade', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Jockey One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Jolly Lodger', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Jomhuria', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Jomolhari', serif", body: "'Inter', sans-serif" },
  { heading: "'Josefin Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Josefin Slab', serif", body: "'Inter', sans-serif" },
  { heading: "'Joti One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Judson', serif", body: "'Inter', sans-serif" },
  { heading: "'Julee', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Julius Sans One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Junge', serif", body: "'Inter', sans-serif" },
  { heading: "'Jura', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Just Another Hand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Just Me Again Down Here', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'K2D', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kadwa', serif", body: "'Inter', sans-serif" },
  { heading: "'Kalam', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kameron', serif", body: "'Inter', sans-serif" },
  { heading: "'Kanit', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kantumruy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Karla', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Karma', serif", body: "'Inter', sans-serif" },
  { heading: "'Katibeh', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kaushan Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kavivanar', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kavoon', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kdam Thmor', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Keania One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kelly Slab', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kenia', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Khand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Khmer', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Khula', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kirang Haerang', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kite One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Knewave', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'KoHo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kodchasan', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kosugi', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kosugi Maru', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kotta One', serif", body: "'Inter', sans-serif" },
  { heading: "'Koulen', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kranky', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kreon', serif", body: "'Inter', sans-serif" },
  { heading: "'Kristi', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Krona One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Krub', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kulim Park', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kumar One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kumar One Outline', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Kurale', serif", body: "'Inter', sans-serif" },
  { heading: "'La Belle Aurore', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Laila', serif", body: "'Inter', sans-serif" },
  { heading: "'Lakki Reddy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lalezar', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lancelot', serif", body: "'Inter', sans-serif" },
  { heading: "'Lateef', serif", body: "'Inter', sans-serif" },
  { heading: "'Lato', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'League Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Leckerli One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ledger', serif", body: "'Inter', sans-serif" },
  { heading: "'Lekton', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lemon', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lemonada', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Barcode 128', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Barcode 39', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Barcode 39 Extended', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Barcode 39 Extended Text', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Barcode 39 Text', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Baskerville', serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Caslon Display', serif", body: "'Inter', sans-serif" },
  { heading: "'Libre Caslon Text', serif", body: "'Inter', sans-serif" },
  { heading: "'Life Savers', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lilita One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lily Script One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Limelight', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Linden Hill', serif", body: "'Inter', sans-serif" },
  { heading: "'Lobster Two', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Londrina Outline', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Londrina Shadow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Londrina Solid', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lora', serif", body: "'Inter', sans-serif" },
  { heading: "'Love Ya Like A Sister', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Loved by the King', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lovers Quarrel', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Luckiest Guy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Lusitana', serif", body: "'Inter', sans-serif" },
  { heading: "'Lustria', serif", body: "'Inter', sans-serif" },
  { heading: "'Macondo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Macondo Swash Caps', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mada', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Magra', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Maiden Orange', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Maitree', serif", body: "'Inter', sans-serif" },
  { heading: "'Mako', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mallanna', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mandali', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Manuale', serif", body: "'Inter', sans-serif" },
  { heading: "'Marcellus', serif", body: "'Inter', sans-serif" },
  { heading: "'Marcellus SC', serif", body: "'Inter', sans-serif" },
  { heading: "'Marck Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Margarine', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Marko One', serif", body: "'Inter', sans-serif" },
  { heading: "'Marmelad', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Martel', serif", body: "'Inter', sans-serif" },
  { heading: "'Martel Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Marvel', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mate', serif", body: "'Inter', sans-serif" },
  { heading: "'Mate SC', serif", body: "'Inter', sans-serif" },
  { heading: "'Maven Pro', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'McLaren', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Meddon', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'MedievalSharp', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Medula One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Megrim', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Meie Script', serif", body: "'Inter', sans-serif" },
  { heading: "'Merienda', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Merienda One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Merriweather', serif", body: "'Inter', sans-serif" },
  { heading: "'Merriweather Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Metal', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Metal Mania', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Metamorphous', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Metrophobic', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Michroma', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Milonga', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Miltonian', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Miltonian Tattoo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Miniver', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Miriam Libre', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mirza', serif", body: "'Inter', sans-serif" },
  { heading: "'Miss Fajardose', cursive", body: "'Inter', sans-serif" },
  { heading: "'Mitr', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Modak', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Modern Antiqua', serif", body: "'Inter', sans-serif" },
  { heading: "'Mogra', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Molengo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Molle', cursive", body: "'Inter', sans-serif" },
  { heading: "'Monda', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Monofett', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Monoton', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Monsieur La Doulaise', cursive", body: "'Inter', sans-serif" },
  { heading: "'Montaga', serif", body: "'Inter', sans-serif" },
  { heading: "'Montez', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Montserrat', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Montserrat Alternates', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Montserrat Subrayada', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Moul', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Moulpali', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mountains of Christmas', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mouse Memoirs', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mr Bedfort', cursive", body: "'Inter', sans-serif" },
  { heading: "'Mr Dafoe', cursive", body: "'Inter', sans-serif" },
  { heading: "'Mr De Haviland', cursive", body: "'Inter', sans-serif" },
  { heading: "'Mrs Saint Delafield', cursive", body: "'Inter', sans-serif" },
  { heading: "'Mrs Sheppards', cursive", body: "'Inter', sans-serif" },
  { heading: "'Mukta', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mukta Mahee', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mukta Malar', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mukta Vaani', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Muli', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Mystery Quest', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'NTR', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nanum Brush Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nanum Gothic', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nanum Gothic Coding', monospace", body: "'Inter', sans-serif" },
  { heading: "'Nanum Myeongjo', serif", body: "'Inter', sans-serif" },
  { heading: "'Nanum Pen Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Neucha', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Neuton', serif", body: "'Inter', sans-serif" },
  { heading: "'New Rocker', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'News Cycle', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Niconne', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nixie One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nobile', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nokora', serif", body: "'Inter', sans-serif" },
  { heading: "'Norican', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nosifer', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nothing You Could Do', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Noticia Text', serif", body: "'Inter', sans-serif" },
  { heading: "'Noto Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Noto Serif', serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Cut', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Flat', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'Nova Oval', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Round', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Slim', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nova Square', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Numans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nunito', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Nunito Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Odor Mean Chey', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Offside', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Old Standard TT', serif", body: "'Inter', sans-serif" },
  { heading: "'Oldenburg', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Oleo Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Oleo Script Swash Caps', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Open Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Open Sans Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Oranienbaum', serif", body: "'Inter', sans-serif" },
  { heading: "'Orbitron', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Oregano', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Orienta', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Original Surfer', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Oswald', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Over the Rainbow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Overlock', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Overlock SC', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Overpass', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Overpass Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'Ovo', serif", body: "'Inter', sans-serif" },
  { heading: "'Oxygen', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Oxygen Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'PT Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'PT Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'PT Sans Caption', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'PT Sans Narrow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'PT Serif', serif", body: "'Inter', sans-serif" },
  { heading: "'PT Serif Caption', serif", body: "'Inter', sans-serif" },
  { heading: "'Pacifico', cursive", body: "'Inter', sans-serif" },
  { heading: "'Palanquin', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Palanquin Dark', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pangolin', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Paprika', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Parisienne', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Passero One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Passion One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pathway Gothic One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Patrick Hand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Patrick Hand SC', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pattaya', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Patua One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pavanam', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Paytone One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Peddana', serif", body: "'Inter', sans-serif" },
  { heading: "'Peralta', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Permanent Marker', cursive", body: "'Inter', sans-serif" },
  { heading: "'Petit Formal Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Petrona', serif", body: "'Inter', sans-serif" },
  { heading: "'Philosopher', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Piedra', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pinyon Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pirata One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Plaster', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Play', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Playball', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Playfair Display', serif", body: "'Inter', sans-serif" },
  { heading: "'Playfair Display SC', serif", body: "'Inter', sans-serif" },
  { heading: "'Podkova', serif", body: "'Inter', sans-serif" },
  { heading: "'Poiret One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Poller One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Poly', serif", body: "'Inter', sans-serif" },
  { heading: "'Pompiere', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Pontano Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Poppins', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Port Lligat Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Port Lligat Slab', serif", body: "'Inter', sans-serif" },
  { heading: "'Pragati Narrow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Prata', serif", body: "'Inter', sans-serif" },
  { heading: "'Preahvihear', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Press Start 2P', monospace", body: "'Inter', sans-serif" },
  { heading: "'Princess Sofia', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Prociono', serif", body: "'Inter', sans-serif" },
  { heading: "'Prompt', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Prosto One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Proza Libre', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Puritan', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Purple Purse', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Quando', serif", body: "'Inter', sans-serif" },
  { heading: "'Quantico', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Quattrocento', serif", body: "'Inter', sans-serif" },
  { heading: "'Quattrocento Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Questrial', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Quicksand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Quintessential', serif", body: "'Inter', sans-serif" },
  { heading: "'Qwigley', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Racing Sans One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Radley', serif", body: "'Inter', sans-serif" },
  { heading: "'Rajdhani', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rakkas', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Raleway', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Raleway Dots', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ramabhadra', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ramaraja', serif", body: "'Inter', sans-serif" },
  { heading: "'Rambla', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rammetto One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ranchers', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rancho', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ranga', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rasa', serif", body: "'Inter', sans-serif" },
  { heading: "'Rationale', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ravi Prakash', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Redressed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Reem Kufi', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Reenie Beanie', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Revalia', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rhodium Libre', serif", body: "'Inter', sans-serif" },
  { heading: "'Ribeye', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ribeye Marrow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Righteous', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Risque', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Roboto', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Roboto Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Roboto Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'Roboto Slab', serif", body: "'Inter', sans-serif" },
  { heading: "'Rochester', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rock Salt', cursive", body: "'Inter', sans-serif" },
  { heading: "'Rokkitt', serif", body: "'Inter', sans-serif" },
  { heading: "'Romanesco', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ropa Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rosario', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rosarivo', serif", body: "'Inter', sans-serif" },
  { heading: "'Rouge Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rozha One', serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik Mono One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik Moonrocks', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik Puddles', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rubik Wet Paint', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ruda', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rufina', serif", body: "'Inter', sans-serif" },
  { heading: "'Ruge Boogie', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ruluko', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rum Raisin', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ruslan Display', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Russo One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ruthie', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Rye', serif", body: "'Inter', sans-serif" },
  { heading: "'Sacramento', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sahitya', serif", body: "'Inter', sans-serif" },
  { heading: "'Sail', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Saira', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Saira Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Saira Extra Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Saira Semi Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Salsa', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sanchez', serif", body: "'Inter', sans-serif" },
  { heading: "'Sancreek', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sansita', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sarala', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sarina', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sarpanch', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Satisfy', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Scada', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Scheherazade', serif", body: "'Inter', sans-serif" },
  { heading: "'Schoolbell', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Scope One', serif", body: "'Inter', sans-serif" },
  { heading: "'Seaweed Script', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Secular One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sedgwick Ave', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sedgwick Ave Display', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sevillana', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Seymour One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Shadows Into Light', cursive", body: "'Inter', sans-serif" },
  { heading: "'Shadows Into Light Two', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Shanti', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Share', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Share Tech', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Share Tech Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'Shojumaru', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Short Stack', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Shrikhand', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Siemreap', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sigmar One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Signika', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Signika Negative', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Simonetta', serif", body: "'Inter', sans-serif" },
  { heading: "'Sintony', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sirin Stencil', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Six Caps', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Skranji', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Slabo 13px', serif", body: "'Inter', sans-serif" },
  { heading: "'Slabo 27px', serif", body: "'Inter', sans-serif" },
  { heading: "'Slackey', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Smokum', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Smythe', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sniglet', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Snippet', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Snowburst One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sofadi One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sofia', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sonsie One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sorts Mill Goudy', serif", body: "'Inter', sans-serif" },
  { heading: "'Source Code Pro', monospace", body: "'Inter', sans-serif" },
  { heading: "'Source Sans Pro', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Source Serif Pro', serif", body: "'Inter', sans-serif" },
  { heading: "'Space Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'Special Elite', monospace", body: "'Inter', sans-serif" },
  { heading: "'Spicy Rice', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Spirax', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Squada One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sree Krushnadevaraya', serif", body: "'Inter', sans-serif" },
  { heading: "'Sriracha', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stalemate', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stalinist One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stardos Stencil', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stint Ultra Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stint Ultra Expanded', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stoke', serif", body: "'Inter', sans-serif" },
  { heading: "'Strait', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Stylish', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sue Ellen Francisco', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Suez One', serif", body: "'Inter', sans-serif" },
  { heading: "'Sumana', serif", body: "'Inter', sans-serif" },
  { heading: "'Sunflower', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sunshiney', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Supermercado One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Sura', serif", body: "'Inter', sans-serif" },
  { heading: "'Suranna', serif", body: "'Inter', sans-serif" },
  { heading: "'Suravaram', serif", body: "'Inter', sans-serif" },
  { heading: "'Suwannaphum', serif", body: "'Inter', sans-serif" },
  { heading: "'Swanky and Moo Moo', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Syncopate', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Tangerine', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Taprom', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Tauri', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Taviraj', serif", body: "'Inter', sans-serif" },
  { heading: "'Teko', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Telex', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Tenor Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Text Me One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'The Girl Next Door', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Tienne', serif", body: "'Inter', sans-serif" },
  { heading: "'Tillana', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Timmana', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Tinos', serif", body: "'Inter', sans-serif" },
  { heading: "'Titan One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Titillium Web', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Trade Winds', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Trirong', serif", body: "'Inter', sans-serif" },
  { heading: "'Trocchi', serif", body: "'Inter', sans-serif" },
  { heading: "'Trochut', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Trykker', serif", body: "'Inter', sans-serif" },
  { heading: "'Tulpen One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ubuntu', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ubuntu Condensed', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Ubuntu Mono', monospace", body: "'Inter', sans-serif" },
  { heading: "'Ultra', serif", body: "'Inter', sans-serif" },
  { heading: "'Uncial Antiqua', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Underdog', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Unica One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'UnifrakturCook', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'UnifrakturMaguntia', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Unkempt', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Unlock', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Unna', serif", body: "'Inter', sans-serif" },
  { heading: "'VT323', monospace", body: "'Inter', sans-serif" },
  { heading: "'Vampiro One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Varela', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Varela Round', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Vast Shadow', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Vesper Libre', serif", body: "'Inter', sans-serif" },
  { heading: "'Vibes', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Vidaloka', serif", body: "'Inter', sans-serif" },
  { heading: "'Viga', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Voces', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Volkhov', serif", body: "'Inter', sans-serif" },
  { heading: "'Vollkorn', serif", body: "'Inter', sans-serif" },
  { heading: "'Voltaire', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Waiting for the Sunrise', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Wallpoet', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Walter Turncoat', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Warnes', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Wellfleet', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Wendy One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Wire One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Work Sans', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Yanone Kaffeesatz', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Yantramanav', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Yatra One', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Yellowtail', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Yeseva One', serif", body: "'Inter', sans-serif" },
  { heading: "'Yesteryear', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Yrsa', serif", body: "'Inter', sans-serif" },
  { heading: "'Zeyada', sans-serif", body: "'Inter', sans-serif" },
  { heading: "'Zilla Slab', serif", body: "'Inter', sans-serif" },
  { heading: "'Zilla Slab Highlight', serif", body: "'Inter', sans-serif" },
  // System fonts (no loading needed)
  { heading: 'system-ui, -apple-system, sans-serif', body: "'Inter', sans-serif" },
  { heading: 'Georgia, serif', body: "'Inter', sans-serif" },
  { heading: '"Courier New", monospace', body: "'Inter', sans-serif" },
];
